import { test } from 'node:test';
import assert from 'node:assert/strict';
import { initial, stories, resolve, advance, budget, finance, fraud, finish, rest, contracts, canChoose, commitments, load, save, KEY } from '../src/engine.ts';
function until(s,step){while(s.step<step){if(!s.resolved)resolveStep(s);advance(s);}return s;}
function resolveStep(s,choices={}){const ev=stories[s.step];if(ev.kind==='budget')budget(s,[280,345,150,200]);else if(ev.kind==='finance')finance(s,choices.finance??0);else if(ev.kind==='fraud')fraud(s,choices.fraud??true,3);else if(ev.kind==='final')finish(s);else resolve(s,choices[s.step]??0);}
function month(choices={},allocation=[280,345,150,200]){const s=initial();while(!s.finished){if(s.step===1)budget(s,allocation);else resolveStep(s,choices);if(!s.finished)advance(s);}return s;}
test('salary and every booked transaction reconcile to the cent',()=>{const s=month();assert.equal(s.day,30);assert.equal(s.finished,true);assert.equal(s.money,10500);assert.equal(s.savings,25000);assert.equal(s.project,30000);assert.equal(s.money,12500+s.ledger.reduce((a,e)=>a+e.amount,0));assert.equal(s.bills.reduce((a,b)=>a+b.amount,0),80000);assert.ok(s.bills.every(b=>b.paid));});
test('events cannot duplicate salary, project transfers or recurring bills',()=>{const s=initial();resolve(s);resolve(s);assert.equal(s.money,177500);advance(s);budget(s,[280,345,150,200]);budget(s,[280,345,150,200]);assert.equal(s.money,142500);advance(s);assert.equal(s.money,80500);advance(s);assert.equal(s.day,4);assert.equal(s.ledger.filter(e=>e.label==='Loyer').length,1);});
test('budget must balance and savings are transfers, not vanished money',()=>{const s=until(initial(),1);assert.throws(()=>budget(s,[0,0,0,0]));assert.throws(()=>budget(s,[975,-5,5,0]));assert.throws(()=>budget(s,[1.2,3,4,966.8]));budget(s,[280,345,150,200]);assert.equal(s.money+s.savings+s.project,177500);});
test('financing totals include all fees and future obligations',()=>{for(let i=0;i<3;i++){const s=until(initial(),6);s.flags.needsPhone=true;const before=s.money;finance(s,i);assert.equal(before-s.money+commitments(s)-s.bills.filter(b=>!b.paid).reduce((a,b)=>a+b.amount,0),contracts[i].total);assert.equal(s.future.reduce((a,b)=>a+b.amount,0),contracts[i].total-contracts[i].today);}});
test('a repaired phone is not bought again in the comparison game',()=>{const s=until(initial(),6);const before=s.money;finance(s,2);assert.equal(s.money,before);assert.equal(s.future.length,0);});
test('no cash at financing still leaves a free playable path',()=>{const s=until(initial(),6);s.flags.needsPhone=true;s.money=0;assert.throws(()=>finance(s,0));finance(s,3);assert.equal(s.resolved,true);assert.equal(s.money,0);assert.equal(s.future.length,0);});
test('fraud protection and simulated loss have distinct consequences',()=>{const safe=until(initial(),8),unsafe=structuredClone(safe);fraud(safe,true,3);fraud(unsafe,false,1);assert.equal(safe.money-unsafe.money,3900);assert.equal(safe.flags.fraudReported,true);assert.equal(unsafe.flags.fraudReported,false);});
test('water reserve draw preserves accounting and deferral records later payments',()=>{for(const choice of [0,1,2]){const s=until(initial(),10);const before=s.money+s.savings;resolve(s,choice);const after=s.money+s.savings;assert.equal(before-after,choice===2?2500:7500);if(choice===2)assert.equal(s.future.reduce((a,b)=>a+b.amount,0),5000);}});
test('small grocery baskets increase the later grocery expense',()=>{const s=month({3:2});assert.equal(s.ledger.find(e=>e.label==='Deuxième panier').amount,-9000);const full=month({3:0});assert.equal(full.ledger.find(e=>e.label==='Deuxième panier').amount,-6000);});
test('several strategies reach day 30 without requiring one winning solution',()=>{for(const strategy of [{},{3:1,4:1,5:1,finance:2,7:0,fraud:false,10:2,11:2,12:2,13:1,14:2},{3:2,4:2,5:2,7:2,10:1,11:1,12:0,13:0,14:0}]){const s=month(strategy);assert.equal(s.finished,true);assert.ok(s.energy>=0&&s.energy<=100);assert.equal(s.money,12500+s.ledger.reduce((a,e)=>a+e.amount,0));}});
test('rests are limited per stage and do not change money',()=>{const s=initial();rest(s);assert.equal(s.energy,77);rest(s);assert.equal(s.energy,77);assert.equal(s.money,12500);s.energy=99;s.rested=-1;rest(s);assert.equal(s.energy,100);});
test('project top-up reserves the final meal and respects the goal',()=>{const s=until(initial(),14);const before=s.money;resolve(s,0);assert.ok(s.money>=2000);assert.ok(s.project<=s.goal);assert.ok(before-s.money<=15000);});
test('discretionary savings cannot spend money needed for the end of month',()=>{const s=until(initial(),11);s.money=3500;assert.equal(canChoose(s,stories[11].choices[0]),false);assert.equal(canChoose(s,stories[11].choices[2]),true);});
test('save/load round-trip and corrupt save handling',()=>{const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)??null,setItem:(k,v)=>storage.set(k,v)};const s=month();assert.equal(save(s),true);assert.deepEqual(load(),s);storage.set(KEY,'broken');assert.equal(load(),null);storage.set(KEY,JSON.stringify({...s,money:'oops'}));assert.equal(load(),null);storage.set(KEY,JSON.stringify({...s,step:50}));assert.equal(load(),null);globalThis.localStorage={setItem(){throw Error('denied')},getItem(){throw Error('denied')}};assert.equal(save(s),false);assert.equal(load(),null);});
test('500 deterministic varied playthroughs preserve balances and always offer a path',()=>{let seed=30;const random=n=>{seed=(1664525*seed+1013904223)>>>0;return seed%n;};for(let run=0;run<500;run++){const s=initial([30000,38000,45000][random(3)],'Projet',random(3),random(3));while(!s.finished){const ev=stories[s.step];if(ev.kind==='budget'){const a=random(196)*5,b=random((975-a)/5+1)*5,c=random((975-a-b)/5+1)*5;budget(s,[a,b,c,975-a-b-c]);}else if(ev.kind==='finance'){const viable=contracts.map((c,i)=>!s.flags.needsPhone||c.today<=s.money?i:null).filter(i=>i!==null);finance(s,[...viable,3][random(viable.length+1)]);}else if(ev.kind==='fraud')fraud(s,random(2)===1,random(4));else if(ev.kind==='final')finish(s);else{const viable=ev.choices.map((c,i)=>canChoose(s,c)?i:null).filter(i=>i!==null);assert.ok(viable.length,`No choice at step ${s.step}`);resolve(s,viable[random(viable.length)]);}assert.equal(s.money,12500+s.ledger.reduce((a,e)=>a+e.amount,0));assert.ok(s.savings>=0&&s.project>=0&&s.energy>=0&&s.energy<=100);if(!s.finished)advance(s);}assert.ok(s.bills.every(b=>b.paid));}});
