import { test, expect, type Page, type Locator } from '@playwright/test';
const snapshot=(page:Page)=>page.evaluate(()=> (window as unknown as {__J30__:any}).__J30__);
const points:Record<string,{x:number;y:number}>={home:{x:195,y:340},bank:{x:393,y:445},market:{x:577,y:340},cafe:{x:180,y:610},atelier:{x:580,y:611},park:{x:390,y:760}};
const route=['home','bank','home','market','cafe','atelier','atelier','market','home','market','home','bank','park','cafe','bank','home'];
async function launch(page:Page){await page.goto('/');await page.getByRole('button',{name:'Commencer mon mois'}).click();await page.getByRole('button',{name:'Tenue corail'}).click();await page.getByRole('button',{name:'Bienvenue dans le quartier'}).click();await expect(page.locator('canvas')).toBeVisible();await page.waitForFunction(()=>!!(window as any).__J30__?.position?.x);}
async function reachEvent(page:Page){const s=await snapshot(page);const place=route[s.state.step];await page.locator('#guide').click();if(place==='home'&&s.position.inside){await page.locator('#interact').click();return;}const p=points[place];await page.waitForFunction(p=>{const w=(window as any).__J30__;return w.position&&!w.position.inside&&Math.hypot(w.position.x-p.x,w.position.y-p.y)<60;},p);if(place==='home'){await page.locator('#interact').click();await page.waitForFunction(()=>(window as any).__J30__.position.inside);await expect(page.locator('#interact')).toHaveText('Interagir ✦');}await page.locator('#interact').click();await expect(page.locator('.sheet')).toBeVisible();}
async function drag(page:Page,source:Locator,target:Locator){await source.scrollIntoViewIfNeeded();const s=(await source.boundingBox())!;await page.mouse.move(s.x+s.width/2,s.y+s.height/2);await page.mouse.down();await target.scrollIntoViewIfNeeded();const t=(await target.boundingBox())!;await page.mouse.move(t.x+t.width/2,t.y+t.height/2,{steps:15});await page.mouse.up();}
async function slider(page:Page,selector:string,value:number){const input=page.locator(selector);await input.scrollIntoViewIfNeeded();const box=(await input.boundingBox())!;const min=Number(await input.getAttribute('min')),max=Number(await input.getAttribute('max'));const x=box.x+8+(box.width-16)*(value-min)/(max-min);await page.mouse.move(x,box.y+box.height/2);await page.mouse.down();await page.mouse.up();}
test('complete a month on a 390 × 844 phone through all three tactile games',async({page})=>{const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await launch(page);await page.screenshot({path:'test-results/mobile-town.png'});const before=(await snapshot(page)).position;const joystick=page.locator('.joystick');const j=(await joystick.boundingBox())!;await page.mouse.move(j.x+j.width/2,j.y+j.height/2);await page.mouse.down();await page.mouse.move(j.x+j.width/2+29,j.y+j.height/2);await page.waitForFunction(x=>(window as any).__J30__.position.x>x+40,before.x,{timeout:15000});await page.mouse.up();expect((await snapshot(page)).position.x).toBeGreaterThan(before.x+40);
 for(let step=0;step<16;step++){await reachEvent(page);if(step===1){await slider(page,'#alloc-2',100);await page.locator('#balance').click();await page.locator('#allocate').click();expect((await snapshot(page)).state.savings).toBeGreaterThan(0);}else if(step===6){for(let i=0;i<3;i++)await drag(page,page.locator(`[data-contract="${i}"]`),page.locator(`[data-slot="${i}"]`));await page.locator('#check-rank').click();await expect(page.locator('#financing-choice')).toBeVisible();await slider(page,'#month',3);await page.screenshot({path:'test-results/mobile-finance.png'});await page.locator('[data-pay="0"]').click();}else if(step===8){for(let i=0;i<3;i++)await page.locator(`[data-clue="${i}"]`).click();await drag(page,page.locator('#sms-token'),page.locator('[data-action="report"]'));await page.locator('#confirm-fraud').click();expect((await snapshot(page)).state.flags.fraudReported).toBe(true);}else if(step===15){await expect(page.getByRole('button',{name:'Rejouer une autre histoire'})).toBeVisible();break;}else{await page.locator('[data-choice]').first().click();}await expect(page.locator('#next')).toBeVisible();if(step===3){const old=(await snapshot(page)).state;await page.reload();await page.getByRole('button',{name:/Reprendre/}).click();await page.waitForFunction(()=>!!(window as any).__J30__.position?.x);expect((await snapshot(page)).state).toEqual(old);}await page.locator('#next').click();}
 const final=(await snapshot(page)).state;expect(final.finished).toBe(true);expect(final.day).toBe(30);expect(final.money).toBe(12500+final.ledger.reduce((a:number,e:any)=>a+e.amount,0));expect(final.color).toBe(1);expect(errors).toEqual([]);await page.screenshot({path:'test-results/mobile-summary.png'});await page.getByRole('button',{name:'Consulter tous mes comptes'}).click();await expect(page.getByText('Historique vérifiable')).toBeVisible();});
test('small phone and landscape stay usable; save survives returning to title',async({page})=>{await page.setViewportSize({width:360,height:640});await launch(page);await expect(page.locator('.nav')).toBeInViewport();await expect(page.locator('.joystick')).toBeInViewport();await page.locator('#wallet').click();await expect(page.locator('.close')).toBeInViewport();await page.locator('.close').click();await page.setViewportSize({width:844,height:390});await page.locator('#journal').click();await page.getByRole('button',{name:'Sauvegarder et revenir à l’accueil'}).click();await expect(page.getByRole('button',{name:/Reprendre/})).toBeVisible();});
test('production service worker can reopen an already visited game offline',async({page,context})=>{const logs:string[]=[];page.on('console',m=>{if(m.type()==='warning'||m.type()==='error')logs.push(m.text());});await launch(page);try{await page.waitForFunction(()=>navigator.serviceWorker.controller!==null,null,{timeout:20000});}catch(error){console.log('SW diagnostics',logs,await page.evaluate(async()=>({url:location.href,secure:isSecureContext,registrations:(await navigator.serviceWorker.getRegistrations()).map(r=>({scope:r.scope,active:r.active?.state,installing:r.installing?.state,waiting:r.waiting?.state}))})));throw error;}await page.reload();await expect(page.getByRole('button',{name:/Reprendre/})).toBeVisible();await context.setOffline(true);await page.reload();await page.getByRole('button',{name:/Reprendre/}).click();await expect(page.locator('canvas')).toBeVisible();await context.setOffline(false);});
