export const euro = (cents: number) => new Intl.NumberFormat('fr-FR', {style:'currency',currency:'EUR',maximumFractionDigits:cents % 100 === 0 ? 0 : 2}).format(cents / 100);
export type Place = 'home'|'market'|'cafe'|'atelier'|'park'|'bank';
export type Entry = {day:number;label:string;amount:number;category:string};
export type Bill = {day:number;label:string;amount:number;paid:boolean};
export type State = {version:1;day:number;step:number;resolved:boolean;money:number;energy:number;savings:number;project:number;goal:number;goalName:string;color:number;skin:number;ledger:Entry[];bills:Bill[];future:Bill[];notes:string[];flags:Record<string,boolean>;plan:number[];rested:number;finished:boolean};
export type Effect = {money?:number;energy?:number;savings?:number;project?:number;note?:string;flag?:string;future?:Bill[]};
export type Choice = {label:string;detail:string;effect:Effect};
export type Story = {day:number;place:Place;title:string;from:string;text:string;kind?:'budget'|'fraud'|'finance'|'final';choices?:Choice[]};
export const stories:Story[] = [
 {day:1,place:'home',title:'Premier salaire !',from:'Votre employeur',text:'1 650 € net arrivent sur votre compte. Le mois commence avec 125 € déjà disponibles. Un projet vous attend… et un loyer aussi.',choices:[{label:'C’est parti !',detail:'+1 650 € · votre premier mois',effect:{money:165000,energy:5,note:'Le salaire est un revenu, pas une somme entièrement disponible : les charges à venir doivent être réservées.'}}]},
 {day:2,place:'bank',title:'À chaque euro sa place',from:'Inès · conseillère associative',text:'Après les 800 € de charges du mois, vous avez 975 € à répartir. Prévoyez vos courses, vos loisirs, une réserve et votre projet. Les enveloppes ne sont pas des dépenses.',kind:'budget'},
 {day:4,place:'home',title:'Un toit, un budget',from:'Votre appartement',text:'Le loyer de 620 € vient d’être prélevé. Une soirée tranquille ou une livraison pour fêter votre installation ?',choices:[{label:'Cuisiner chez moi',detail:'12 € · équilibre +8',effect:{money:-1200,energy:8}},{label:'Partager une livraison',detail:'28 € · équilibre +13',effect:{money:-2800,energy:13,note:'Un plaisir peut avoir sa place dans un budget. Le rendre visible aide à choisir.'}}]},
 {day:6,place:'market',title:'Le panier de la semaine',from:'Malik · épicier',text:'Il faut remplir le frigo. Un panier planifié dure plus longtemps ; les plats prêts rendent service quand l’énergie manque.',choices:[{label:'Un panier à cuisiner',detail:'55 € · demande un peu d’énergie',effect:{money:-5500,energy:-5,flag:'cooking'}},{label:'Pratique et rapide',detail:'78 € · équilibre +8',effect:{money:-7800,energy:8}},{label:'Les essentiels du moment',detail:'35 € · prochaines courses plus tôt',effect:{money:-3500,energy:-3,flag:'smallBasket'}}]},
 {day:8,place:'cafe',title:'On se retrouve ce soir ?',from:'Lou · votre amie',text:'Lou propose une soirée. Se faire du bien compte aussi. Elle est tout aussi partante pour un pique-nique au parc.',choices:[{label:'Un pique-nique ensemble',detail:'8 € · équilibre +14',effect:{money:-800,energy:14,flag:'friends'}},{label:'Concert et café',detail:'42 € · équilibre +22',effect:{money:-4200,energy:22,flag:'friends'}},{label:'Ce soir, je me repose',detail:'0 € · équilibre +7',effect:{energy:7}}]},
 {day:10,place:'atelier',title:'L’écran fait des siennes',from:'Sam · atelier de réparation',text:'Votre téléphone est tombé. Sam peut le réparer pour 90 €, ou proposer un appareil reconditionné. Un coup dur n’est pas une faute personnelle.',choices:[{label:'Réparer mon téléphone',detail:'90 € · pas de dette',effect:{money:-9000,energy:-4,flag:'repaired'}},{label:'Étudier le remplacement',detail:'Comparer comptant et paiements fractionnés',effect:{flag:'needsPhone'}},{label:'Utiliser un ancien téléphone',detail:'0 € · équilibre −10 · compatible avec le travail',effect:{energy:-10,flag:'oldPhone'}}]},
 {day:12,place:'atelier',title:'Le vrai prix des mensualités',from:'Sam · atelier de réparation',text:'Même produit, trois financements. Manipulez les contrats, comparez leur coût total et choisissez. Les offres sont fictives ; tous les frais sont indiqués.',kind:'finance'},
 {day:14,place:'market',title:'La vitrine du samedi',from:'Une jolie veste',text:'Cette veste à 65 € vous plaît vraiment. En sortant du travail, l’achat ferait du bien… votre projet aussi.',choices:[{label:'Je me l’offre',detail:'65 € · équilibre +12',effect:{money:-6500,energy:12,note:'L’achat plaisir est un choix. Son coût d’opportunité est ce qu’on ne peut plus financer avec la même somme.'}},{label:'Je laisse passer 48 heures',detail:'0 € · prendre du recul',effect:{energy:3,flag:'waited'}},{label:'Trouver une seconde main',detail:'24 € · équilibre +8',effect:{money:-2400,energy:8}}]},
 {day:16,place:'home',title:'Un SMS très pressé',from:'Votre téléphone',text:'Un message annonce un remboursement urgent. Prenez le temps d’inspecter ce qui cloche, puis glissez le message vers l’action de votre choix.',kind:'fraud'},
 {day:18,place:'market',title:'Le frigo est presque vide',from:'Malik · épicier',text:'Deuxième passage aux courses. Votre premier panier a une conséquence sur ce qu’il reste à acheter.',choices:[{label:'Faire les courses nécessaires',detail:'Panier ajusté à vos achats précédents',effect:{energy:3}},{label:'Panier et repas avec Lou',detail:'Panier ajusté + 15 € · équilibre +15',effect:{money:-1500,energy:15,flag:'friends'}}]},
 {day:20,place:'home',title:'Une facture inattendue',from:'Régularisation d’eau',text:'Une régularisation de 75 € arrive. L’immeuble a eu une fuite. Vous pouvez payer, mobiliser votre réserve ou demander un échéancier sans frais.',choices:[{label:'Payer depuis mon compte',detail:'75 € aujourd’hui',effect:{money:-7500,energy:-3}},{label:'Utiliser ma réserve',detail:'Jusqu’à 75 € d’épargne ; solde depuis le compte',effect:{flag:'useReserve',energy:-1}},{label:'Demander un échéancier',detail:'25 € aujourd’hui + 2 × 25 € les mois suivants · 0 € de frais',effect:{money:-2500,future:[{day:50,label:'Eau · échéance 2/3',amount:2500,paid:false},{day:80,label:'Eau · échéance 3/3',amount:2500,paid:false}],note:'Un échéancier sans frais peut lisser une dépense, mais engage une part du revenu futur.'}}]},
 {day:22,place:'bank',title:'Un coussin pour demain',from:'Inès · conseillère associative',text:'Une réserve réduit le besoin d’emprunter lors d’un prochain imprévu. Elle reste votre argent. Gardez aussi assez sur le compte pour finir le mois.',choices:[{label:'Mettre 100 € en réserve',detail:'Compte −100 € · épargne +100 €',effect:{money:-10000,savings:10000,energy:3}},{label:'Mettre 30 € en réserve',detail:'Compte −30 € · épargne +30 €',effect:{money:-3000,savings:3000,energy:2}},{label:'Garder la liquidité',detail:'0 € · selon mes besoins actuels',effect:{note:'Ne pas pouvoir épargner n’est pas un échec : revenus, logement et imprévus limitent la marge de manœuvre.'}}]},
 {day:24,place:'park',title:'Du temps pour votre projet',from:'Lou · votre amie',text:'Lou vous aide à préparer votre projet. Vous pouvez investir du temps, un peu d’argent ou les deux. La cagnotte restera disponible même si l’objectif est reporté.',choices:[{label:'Une session de préparation',detail:'Projet +40 € de cagnotte · compte −40 € · équilibre −5',effect:{money:-4000,project:4000,energy:-5,flag:'prepared'}},{label:'Préparer et réserver',detail:'Projet +120 € · compte −120 € · équilibre −8',effect:{money:-12000,project:12000,energy:-8,flag:'prepared'}},{label:'Reporter et souffler',detail:'0 € · équilibre +12',effect:{energy:12,note:'Reporter un projet peut être raisonnable : sa valeur ne disparaît pas avec une date.'}}]},
 {day:26,place:'cafe',title:'Un coup de main rémunéré',from:'Lou · votre amie',text:'Le café cherche quelqu’un pour ranger sa réserve cet après-midi. La rémunération nette est de 65 €. Vous avez aussi besoin de repos.',choices:[{label:'Donner un coup de main',detail:'+65 € · équilibre −18',effect:{money:6500,energy:-18,note:'Un revenu complémentaire demande du temps et de l’énergie ; ce n’est pas toujours une option accessible.'}},{label:'Passer mon tour',detail:'0 € · équilibre +12',effect:{energy:12}}]},
 {day:28,place:'bank',title:'Le dernier ajustement',from:'Votre projet',text:'Le mois touche à sa fin. Dernière occasion de répartir ce qui reste. Le repas de fin de mois coûtera encore 20 €.',choices:[{label:'Compléter mon projet',detail:'Au maximum 150 €, en gardant 20 € pour le repas',effect:{flag:'topUp'}},{label:'Renforcer ma réserve',detail:'50 € si le compte le permet',effect:{money:-5000,savings:5000}},{label:'Conserver mon argent disponible',detail:'Garder de la souplesse',effect:{energy:4}}]},
 {day:30,place:'home',title:'Vous êtes jusqu’au 30',from:'Le bilan du mois',text:'Les derniers 20 € de repas sont réglés. Votre mois raconte vos choix, mais aussi les contraintes auxquelles vous avez dû faire face.',kind:'final'}
];
export function initial(goal=30000,goalName='Un vélo pour mes trajets',color=0,skin=0):State {
 return {version:1,day:1,step:0,resolved:false,money:12500,energy:70,savings:0,project:0,goal,goalName,color,skin,ledger:[],bills:[{day:4,label:'Loyer',amount:62000,paid:false},{day:7,label:'Énergie et internet',amount:8500,paid:false},{day:12,label:'Transports',amount:4500,paid:false},{day:22,label:'Téléphone et assurance',amount:5000,paid:false}],future:[],notes:[],flags:{},plan:[280,345,150,200],rested:-1,finished:false};
}
export function transact(s:State,amount:number,label:string,category='vie') {if(!Number.isSafeInteger(amount)) throw Error('Montant non entier');s.money+=amount;s.ledger.push({day:s.day,label,amount,category});}
export function effect(s:State,e:Effect,label:string) {if(e.money)transact(s,e.money,label,e.savings?'épargne':e.project?'projet':'vie');s.energy=Math.max(0,Math.min(100,s.energy+(e.energy||0)));s.savings+=e.savings||0;s.project+=e.project||0;if(e.note)s.notes.push(e.note);if(e.flag)s.flags[e.flag]=true;if(e.future)s.future.push(...e.future.map(b=>({...b})));}
export function resolve(s:State,choice=0) {
 if(s.resolved||s.finished) return;
 const ev=stories[s.step]; const c=ev.choices?.[choice];if(!c)throw Error('Choix invalide');
 if(!canChoose(s,c))throw Error('Solde insuffisant');
 effect(s,c.effect,c.label);
 if(s.step===9) transact(s,-(s.flags.smallBasket?9000:s.flags.cooking?6000:7200),'Deuxième panier','alimentation');
 if(c.effect.flag==='useReserve'){const use=Math.min(7500,s.savings);s.savings-=use;transact(s,use,'Retrait de réserve','épargne');transact(s,-7500,'Régularisation d’eau','charge');}
 if(c.effect.flag==='topUp'){const n=Math.max(0,Math.min(15000,s.goal-s.project,s.money-2000));s.project+=n;transact(s,-n,'Complément de cagnotte','projet');}
 s.resolved=true;
}
export function canChoose(s:State,c:Choice){return !((c.effect.savings||c.effect.project||0)>0 && s.money+(c.effect.money||0)<2000) && (!(c.effect.money&&c.effect.money<0)||s.money+c.effect.money>=0||s.step===10||s.step===2||s.step===3||s.step===9);}
export function budget(s:State,values:number[]){if(s.resolved)return;if(values.length!==4||values.some(v=>!Number.isInteger(v)||v<0)||values.reduce((a,b)=>a+b,0)!==975)throw Error('Répartissez exactement 975 €');s.plan=[...values];effect(s,{money:-(values[2]+values[3])*100,savings:values[2]*100,project:values[3]*100},'Répartition : réserve et projet');s.resolved=true;}
export const contracts=[{name:'Comptant',today:24000,total:24000,future:[] as Bill[],description:'240 € aujourd’hui · aucun frais'},{name:'3 mensualités',today:8400,total:25200,future:[{day:42,label:'Téléphone · 2/3',amount:8400,paid:false},{day:72,label:'Téléphone · 3/3',amount:8400,paid:false}],description:'3 × 84 € · dont 12 € de frais'},{name:'6 mensualités',today:4500,total:27000,future:[42,72,102,132,162].map(day=>({day,label:'Téléphone · mensualité',amount:4500,paid:false})),description:'6 × 45 € · dont 30 € de frais'}];
function stateNeedsPhone(s:State){return !!s.flags.needsPhone;}
export function finance(s:State,index:number){if(s.resolved)return;if(index===3){effect(s,{energy:stateNeedsPhone(s)?-10:3,note:'Vous avez conservé un ancien téléphone utilisable, sans nouvelles mensualités.'},'Conserver un ancien téléphone');s.flags.oldPhone=true;s.resolved=true;return;}const c=contracts[index];if(!c)throw Error('Contrat invalide');if(s.flags.needsPhone){if(s.money<c.today)throw Error('Solde insuffisant pour cette première échéance');effect(s,{money:-c.today,energy:8,future:c.future,note:`Téléphone : coût total ${euro(c.total)}, dont ${euro(c.total-24000)} de frais. ${euro(c.total-c.today)} restent engagés.`},c.name);s.flags.phoneBought=true;}else{s.notes.push('La comparaison montre que 45 € par mois peuvent coûter plus cher que 240 € comptant. Vous avez conservé votre téléphone.');s.energy=Math.min(100,s.energy+3);}s.resolved=true;}
export function fraud(s:State,reported:boolean,clues:number){if(s.resolved)return;effect(s,reported?{energy:3,note:`SMS signalé. ${clues}/3 signaux repérés : urgence artificielle, adresse trompeuse, demande de carte. Vérifiez depuis le site officiel saisi vous-même.`}:{money:-3900,energy:-8,note:'Le faux lien a entraîné un débit simulé de 39 €. En cas réel : contacter sa banque rapidement, faire opposition si nécessaire et signaler le message au 33700. La responsabilité appartient au fraudeur.'},reported?'SMS signalé':'Fraude · débit simulé');s.flags.fraudReported=reported;s.resolved=true;}
export function advance(s:State){if(!s.resolved||s.finished)return;s.step++;const next=stories[s.step];if(!next)throw Error('Fin invalide');const elapsed=next.day-s.day;s.day=next.day;s.energy=Math.max(0,s.energy-elapsed);for(const b of [...s.bills,...s.future])if(!b.paid&&b.day<=s.day){transact(s,-b.amount,b.label,'charge');b.paid=true;}s.resolved=false;if(s.day===30){transact(s,-2000,'Repas de fin de mois','alimentation');}}
export function finish(s:State){if(s.day!==30)throw Error('Mois incomplet');s.finished=true;s.resolved=true;}
export function rest(s:State){if(s.rested===s.step||s.finished)return;s.energy=Math.min(100,s.energy+7);s.rested=s.step;}
export const KEY='jusquau30-v1';
export function save(s:State):boolean{try{localStorage.setItem(KEY,JSON.stringify(s));return true;}catch{return false;}}
export function decodeSave(value:string|null):State|null{
 try{
  const s=JSON.parse(value||'null');
  const integer=(v:unknown)=>Number.isSafeInteger(v);
  const bill=(b:any)=>b&&integer(b.day)&&b.day>0&&typeof b.label==='string'&&integer(b.amount)&&b.amount>=0&&typeof b.paid==='boolean';
  if(!s||s.version!==1||!integer(s.step)||s.step<0||s.step>=stories.length||s.day!==stories[s.step].day||!['money','energy','savings','project','goal','color','skin','rested'].every(k=>integer(s[k]))||s.savings<0||s.project<0||s.goal<=0||s.energy<0||s.energy>100||s.color<0||s.color>2||s.skin<0||s.skin>2||s.rested< -1||s.rested>15||typeof s.goalName!=='string'||typeof s.resolved!=='boolean'||typeof s.finished!=='boolean'||(s.finished&&s.step!==15))return null;
  if(!Array.isArray(s.ledger)||!s.ledger.every((e:any)=>e&&integer(e.day)&&e.day>=1&&e.day<=30&&typeof e.label==='string'&&typeof e.category==='string'&&integer(e.amount))||s.money!==12500+s.ledger.reduce((a:number,e:Entry)=>a+e.amount,0))return null;
  if(!Array.isArray(s.bills)||!s.bills.every(bill)||!Array.isArray(s.future)||!s.future.every(bill)||!Array.isArray(s.notes)||!s.notes.every((n:unknown)=>typeof n==='string')||!Array.isArray(s.plan)||s.plan.length!==4||!s.plan.every((v:unknown)=>integer(v)&&Number(v)>=0)||!s.flags||typeof s.flags!=='object'||Object.values(s.flags).some(v=>typeof v!=='boolean'))return null;
  return s;
 }catch{return null;}
}
export function load():State|null{try{return decodeSave(localStorage.getItem(KEY));}catch{return null;}}
export function commitments(s:State){return [...s.bills,...s.future].filter(b=>!b.paid).reduce((a,b)=>a+b.amount,0);}
